#!/usr/bin/osascript

on run argv

    set toggle to false
    if (count of argv) is greater than 0 then
        set arg1 to item 1 of argv
        if arg1 is "toggle" then
            set toggle to true
        end if
    end if

    tell application "SwitchResX Daemon"
    	activate
        if toggle then
            set gray levels to not (gray levels)
        else
            set gray levels to true
        end if
    end tell

end run
